[package]
name = "client"
version = "0.1.0"
authors = ["Germain Wessely <germain.wessely@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "^0.2", features = ["serde-serialize"] }
yew = "0.19.3"
serde = "1.0"
anyhow = "1"
magic-crypt = "3.1"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8" }
web-sys = { version = "0.3", features = [
    "Clipboard",
    "Navigator",
    "Window",
    "CssStyleDeclaration",
    "HtmlButtonElement",
    "HtmlSelectElement",
    "Url",
    "InputEvent",
    "DataTransfer"
] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
if_chain = "1"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
gloo-net = "0.2.0"

shared = { path = "../shared" }
