[package]
name = "client"
version = "0.1.0"
authors = ["Germain Wessely <germain.wessely@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = {version = "^0.2", features = ["serde-serialize"]}
yew = "0.17"
serde = "1.0"
anyhow = "1"
magic-crypt = "3.1"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8" }
web-sys = { version = "0.3", features = ["Clipboard", "Navigator", "Window"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
if_chain = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }

shared = { path = "../shared" }