version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - "5432"
volumes:
  redis_data:
