[package]
name = "secret_share"
version = "0.1.0"
authors = ["Germain Wessely <germain.wessely@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
actix-files = "0.6.2"
askama = "0.11.1"
serde = "1.0.144"
serde_json = "1.0.85"
env_logger = "0.9.0"
redis = { version = "0.21.6",  features = ["aio", "async-std-comp"] }
uuid = "1.1.2"
lazy_static = "1.4.0"
bcrypt = "0.13.0"
anyhow = "1.0.64"

shared = { path = "../shared"}
