[package]
name = "secret_share"
version = "0.1.0"
authors = ["Germain Wessely <germain.wessely@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
actix-files = "0.5"
askama = "0.10"
serde = "1.0"
serde_json = "1"
env_logger = "0.8"
redis = { version = "0.20",  features = ["aio", "async-std-comp"] }
uuid = "0.8"
lazy_static = "1.4"
bcrypt = "0.9"
anyhow = "1"

shared = { path = "../shared"}
