[package]
name = "client_seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.9.2"
serde-wasm-bindgen = "0.4"
askama = "0.11.1"
if_chain = "1.0.2"

shared = { path = "../shared" }